#!/bin/bash

# Setup script for tedee-scripts
# Helps with initial configuration

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo "========================================"
echo "  Tedee Scripts - Setup"
echo "========================================"
echo

# Check if config exists
if [ -f "$SCRIPT_DIR/config/tedee.conf" ]; then
    echo -e "${GREEN}✓${NC} Configuration found: config/tedee.conf"
    echo
    read -p "Do you want to reconfigure? (y/N): " RECONFIGURE
    echo
    if [ "$RECONFIGURE" != "y" ] && [ "$RECONFIGURE" != "Y" ]; then
        echo -e "${GREEN}Setup complete!${NC}"
        echo
        echo "You can now use:"
        echo "  ./bin/close  - Lock the door"
        echo "  ./bin/update - Update repository"
        exit 0
    fi
else
    echo -e "${YELLOW}!${NC} No configuration found"
    echo
fi

# Interactive configuration
echo "Please enter your Tedee configuration:"
echo "Note: All three fields are mandatory"
echo

# Loop until all mandatory fields are filled
while true; do
    read -p "Bridge IP address: " BRIDGE_IP
    if [ -z "$BRIDGE_IP" ]; then
        echo -e "${RED}✗${NC} Bridge IP is required!"
        continue
    fi
    break
done

while true; do
    read -p "Tedee API Token: " TEDEE_TOKEN
    if [ -z "$TEDEE_TOKEN" ]; then
        echo -e "${RED}✗${NC} Tedee API Token is required!"
        continue
    fi
    break
done

while true; do
    read -p "Device ID: " DEVICE_ID
    if [ -z "$DEVICE_ID" ]; then
        echo -e "${RED}✗${NC} Device ID is required!"
        continue
    fi
    break
done

echo
echo "Optional - Telegram notifications (press Enter to skip):"
read -p "Telegram Bot Token (optional): " TELEGRAM_TOKEN

# Only ask for Chat ID if Telegram Token was provided
if [ -n "$TELEGRAM_TOKEN" ]; then
    # If token is provided, Chat ID becomes mandatory
    while true; do
        read -p "Telegram Chat ID (required): " CHAT_ID
        if [ -z "$CHAT_ID" ]; then
            echo -e "${RED}✗${NC} Chat ID is required when Telegram Token is set!"
            continue
        fi
        break
    done
else
    CHAT_ID=""
fi

# Create config file directly
echo "Creating configuration file..."

cat > "$SCRIPT_DIR/config/tedee.conf" << EOF
#!/bin/sh

# Tedee Bridge Configuration
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')

# ===== MANDATORY SETTINGS =====

# IP address of your Tedee Bridge
BRIDGE_IP="$BRIDGE_IP"

# API Token for Tedee Bridge authentication
TEDEE_TOKEN="$TEDEE_TOKEN"

# Device ID of your Tedee lock
DEVICE_ID="$DEVICE_ID"

# ===== OPTIONAL SETTINGS =====

# Telegram Bot Configuration (for notifications)
TELEGRAM_TOKEN="$TELEGRAM_TOKEN"
CHAT_ID="$CHAT_ID"

# Retry Configuration
MAX_RETRIES=3
SLEEP_BETWEEN=5
EOF

echo
echo -e "${GREEN}✓${NC} Configuration saved successfully!"

# Make scripts executable
chmod +x "$SCRIPT_DIR/bin/"*
echo -e "${GREEN}✓${NC} Scripts are now executable"

echo
echo "========================================"
echo -e "${GREEN}  Setup Complete!${NC}"
echo "========================================"
echo
echo "Available commands:"
echo "  ./bin/close  - Lock the door"
echo "  ./bin/update - Update repository"
echo
echo "To use scripts from anywhere, add to your PATH:"
echo "  export PATH=\"$SCRIPT_DIR/bin:\$PATH\""
echo

